version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      react-native-deps:
        patterns:
          - "react*"
          - "expo*"
    ignore:
      - package-name: "expo"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - package-name: "expo-*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - package-name: "react-native"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
